# SPDX-FileCopyrightText: 2026 Space Station 14 Contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  id: ThrusterRogueMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: Rogue thruster machine board
  components:
  - type: MachineBoard
    prototype: ThrusterRogue
    requirements:
      Manipulator: 1
    stackRequirements:
      Steel: 5
